easy_admin:
    site_name: 'Titane Admin'
    design:
        brand_color: '#1E90FF'
        menu:
            expand_single_child: true
        form_theme: 
            - '@EasyAdmin/form/bootstrap_5_layout.html.twig'
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i'
    dashboards:
        main:
            title: 'Titane Dashboard'
            favicon: '/favicon.ico'
    user:
        display_name_property_path: 'email'
        display_avatar: false
        name_property_path: 'email'
    list:
        actions:
            - { name: 'edit', icon: 'fa fa-pencil', label: false }
            - { name: 'delete', icon: 'fa fa-trash', label: false }
        max_results: 30
    search:
        enabled: true